# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
  # see https://github.com/ruby/setup-ruby
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: [3.4, head]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: install rmagick development
      run: sudo apt install libmagickcore-dev graphicsmagick graphicsmagick-imagemagick-compat

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Replace helvetica by lato
      run: |
        mkdir -p ~/.magick/
        echo '<?xml version="1.0"?>'  > ~/.magick/type.xml
        echo '<typemap>'  >> ~/.magick/type.xml
        echo '<type format="ttf" name="Helvetica" fullname="Helvetica Regular" family="Helvetica" glyphs="/usr/share/fonts/truetype/lato/Lato-Regular.ttf"/>' >> ~/.magick/type.xml
        echo '</typemap>'  >> ~/.magick/type.xml
        cat ~/.magick/type.xml
        convert -list font

    - name: Run tests via test/suite.rb
      run: bundle exec ruby test/suite.rb

    - name: Run spec tests for compositions
      run: bundle exec rspec spec/parslet_spec.rb
